name: Reserveer Boot Automatisch

on:
  schedule:
    - cron: "58 22 * * *"
  workflow_dispatch: {}

jobs:
  reservering:
    runs-on: ubuntu-latest

    steps:
    - name: Repo ophalen
      uses: actions/checkout@v4

    - name: Python installeren
      uses: actions/setup-python@v5
      with:
       python-version: "3.12"

    - name: Playwright installeren
      run: |
        pip install playwright
        playwright install

    - name: Start reserveringsscript
      run: python reservering.py
